server:
  port: 8080
  servlet:
    #    context-path: /api/ws
    session:
      timeout: 604800s
      cookie:
        max-age: 604800s
springdoc:
  swagger-ui:
    path: /swagger-ui.html
dev-auth: true
spring:
  redis:
    host: localhost
    port: 6379
  freemarker:
    expose-request-attributes: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/central_monitor
    username: postgres
    password: 1234
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml

    drop-first: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    jpa:
      show-sql: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
parse:
  page-size: 100
data:
  page-size: 100
market: citilink_monitor
logging:
  level:
    root: DEBUG
coefficient:
  middle:
    buff: 1.2
    debuff: 0.8
  price-info:
    buff: 1.3
    debuff: 0.5
  correct:
    buff: 1.4
    debuff: 0.7
  percent:
    up: 0.97
    down: 1.02
    rating: 0.9
